/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KostManagement.View;

import FormEdit.Edit_Fasilitas;
import FormEdit.Edit_kamar;
import FormEdit.Edit_pelanggan;
import KostManagement.Controller.FasilitasController;
import KostManagement.Controller.KamarController;
import KostManagement.Controller.PelangganController;
import KostManagement.Controller.TransaksiController;
import KostManagement.KoneksiDB;
import KostManagement.Model.KamarModel;
import KostManagement.Model.TransaksiModel;
import KostManagement.View.FormTambah.Tambah_Kamar;
import KostManagement.View.FormTambah.Tambah_fasilitas;
import KostManagement.View.FormTambah.Tambah_pelanggan;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author linggap
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
        halamanUtamaPanel.show();
        pelangganPanel.hide();
        kamarPanel.hide();
        fasilitasPanel.hide();
        transaksiPanel.hide();
        jLabel2.setForeground(Color.yellow);
        tampilDataTransaksiTerakhir();
        tampilDataTransaksi();
        tammpilDataFasilitas();
        tampildatakamar();
        tampildatapelanggan();
        
    }
    
    int row = 0;
    public String tampilFieldKodePelanggan() {
        row = tabelPelanggan.getSelectedColumn();
        String kode = tableTransaksi2.getValueAt(row, 0).toString();
        return kode;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        menu1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menu3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        menu5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        halamanUtamaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi1 = new javax.swing.JTable();
        Close = new javax.swing.JLabel();
        notifikasi = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        notif = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        logokostan = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        tglTerakhir = new javax.swing.JLabel();
        pelangganPanel = new javax.swing.JPanel();
        Close1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        logokostan5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txt_cariData = new javax.swing.JTextField();
        cariData = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        searchBy = new javax.swing.JComboBox<>();
        kamarPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Close2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        logokostan6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableKamar2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        fasilitasPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Close3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        logokostan7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelFasilitas = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        hapusFasilitas = new javax.swing.JLabel();
        editFasilitas = new javax.swing.JLabel();
        tambahFasilitas = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        bycarifasilitas = new javax.swing.JComboBox<>();
        transaksiPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Close4 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        logokostan8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableTransaksi2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txt_cariKode = new javax.swing.JTextField();
        cariKode = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(36, 47, 65));
        sidePane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidePaneMouseDragged(evt);
            }
        });
        sidePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePaneMousePressed(evt);
            }
        });
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu1.setBackground(new java.awt.Color(36, 47, 65));
        menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Home_15px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Halaman Utama");

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        sidePane.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, 40));

        menu4.setBackground(new java.awt.Color(36, 47, 65));
        menu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu4MouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Wi-Fi_15px_1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Fasilitas Kamar ");

        javax.swing.GroupLayout menu4Layout = new javax.swing.GroupLayout(menu4);
        menu4.setLayout(menu4Layout);
        menu4Layout.setHorizontalGroup(
            menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        menu4Layout.setVerticalGroup(
            menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePane.add(menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, 40));

        menu2.setBackground(new java.awt.Color(36, 47, 65));
        menu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_User_Group_Man_Man_15px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data Pelanggan");

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        menu2Layout.setVerticalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePane.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        menu3.setBackground(new java.awt.Color(36, 47, 65));
        menu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu3MouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Double_Bed_15px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data Kamar");

        javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
        menu3.setLayout(menu3Layout);
        menu3Layout.setHorizontalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        menu3Layout.setVerticalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePane.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));
        sidePane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dashboard Admin");
        sidePane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        menu5.setBackground(new java.awt.Color(36, 47, 65));
        menu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu5MouseClicked(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Bill_15px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Transaksi");

        javax.swing.GroupLayout menu5Layout = new javax.swing.GroupLayout(menu5);
        menu5.setLayout(menu5Layout);
        menu5Layout.setHorizontalGroup(
            menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        menu5Layout.setVerticalGroup(
            menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePane.add(menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        bg.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 471));

        halamanUtamaPanel.setBackground(new java.awt.Color(255, 255, 255));
        halamanUtamaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tabelTransaksi1.setAutoCreateRowSorter(true);
        tabelTransaksi1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabelTransaksi1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Kode Transaksi", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelTransaksi1.setGridColor(new java.awt.Color(255, 255, 255));
        tabelTransaksi1.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tabelTransaksi1.setRowHeight(24);
        tabelTransaksi1.setSelectionBackground(new java.awt.Color(51, 255, 255));
        tabelTransaksi1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tabelTransaksi1);
        if (tabelTransaksi1.getColumnModel().getColumnCount() > 0) {
            tabelTransaksi1.getColumnModel().getColumn(0).setResizable(false);
            tabelTransaksi1.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        halamanUtamaPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 770, 160));

        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Delete_15px.png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        halamanUtamaPanel.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, 20));

        notifikasi.setBackground(new java.awt.Color(255, 255, 255));

        notif.setColumns(20);
        notif.setLineWrap(true);
        notif.setRows(5);
        notif.setBorder(null);
        notif.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(notif);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Pemberitahuan ! ! !");

        javax.swing.GroupLayout notifikasiLayout = new javax.swing.GroupLayout(notifikasi);
        notifikasi.setLayout(notifikasiLayout);
        notifikasiLayout.setHorizontalGroup(
            notifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notifikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(notifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGroup(notifikasiLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        notifikasiLayout.setVerticalGroup(
            notifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notifikasiLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        halamanUtamaPanel.add(notifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 790, 110));

        jPanel9.setBackground(new java.awt.Color(0, 150, 136));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Transaksi Terakhir Pada");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));
        jPanel9.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, 10));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 58, 210, 20));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Dasboard/Halaman-Utama");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        jLabel11.setFont(new java.awt.Font("Hobo Std", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("KOST Ibu Tuti");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, -1));

        logokostan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Home_52px_3.png"))); // NOI18N
        jPanel9.add(logokostan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 50));
        jPanel9.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 120, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jl. Kenangan No. 29 Bandung Tlp (022) - 2126453 ");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        tglTerakhir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tglTerakhir.setForeground(new java.awt.Color(255, 255, 255));
        tglTerakhir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tglTerakhir.setText("dd/MM/yyyy");
        jPanel9.add(tglTerakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 120, -1));

        halamanUtamaPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 130));

        bg.add(halamanUtamaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 790, 470));

        pelangganPanel.setBackground(new java.awt.Color(255, 255, 255));
        pelangganPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close1.setForeground(new java.awt.Color(255, 255, 255));
        Close1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Delete_15px.png"))); // NOI18N
        Close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close1MouseClicked(evt);
            }
        });
        pelangganPanel.add(Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, 20));

        jPanel2.setBackground(new java.awt.Color(0, 150, 136));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Dasboard/Data-Pelanggan");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 200, 20));

        jLabel19.setFont(new java.awt.Font("Hobo Std", 1, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("KOST Ibu Tuti");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, -1));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, 10));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Jl. Kenangan No. 29 Bandung Tlp (022) - 2126453 ");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        logokostan5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Home_52px_3.png"))); // NOI18N
        jPanel2.add(logokostan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 50));

        pelangganPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 130));

        tabelPelanggan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pelanggan", "Nama ", "Jenis Kelamin", "Alamat Asal", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelPelanggan);
        if (tabelPelanggan.getColumnModel().getColumnCount() > 0) {
            tabelPelanggan.getColumnModel().getColumn(0).setResizable(false);
            tabelPelanggan.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        pelangganPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 770, 190));

        jLabel15.setText("Menurut");
        pelangganPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, 20));
        pelangganPanel.add(txt_cariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, -1));

        cariData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Search_15px_1.png"))); // NOI18N
        cariData.setToolTipText("Cari");
        cariData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cariData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariDataMouseClicked(evt);
            }
        });
        pelangganPanel.add(cariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 20, 20));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Plus_30px.png"))); // NOI18N
        jLabel37.setToolTipText("Tambah");
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        pelangganPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 30, 50));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Edit_Property_30px.png"))); // NOI18N
        jLabel39.setToolTipText("Edit");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        pelangganPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 40, 30));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Trash_30px.png"))); // NOI18N
        jLabel43.setToolTipText("Hapus");
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pelangganPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        jLabel53.setText("Cari Pelanggan");
        pelangganPanel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        searchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "Nama" }));
        searchBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByActionPerformed(evt);
            }
        });
        pelangganPanel.add(searchBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        bg.add(pelangganPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 790, 470));

        kamarPanel.setBackground(new java.awt.Color(255, 255, 255));
        kamarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 150, 136));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 58, 210, 20));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Dasboard/Data-Kamar");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 160, -1));

        Close2.setForeground(new java.awt.Color(255, 255, 255));
        Close2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Delete_15px.png"))); // NOI18N
        Close2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close2MouseClicked(evt);
            }
        });
        jPanel3.add(Close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, 20));

        jLabel22.setFont(new java.awt.Font("Hobo Std", 1, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("KOST Ibu Tuti");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, -1));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, 10));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Jl. Kenangan No. 29 Bandung Tlp (022) - 2126453 ");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        logokostan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Home_52px_3.png"))); // NOI18N
        jPanel3.add(logokostan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 50));

        kamarPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 130));

        TableKamar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TableKamar2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Kode Transaksi", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableKamar2);
        if (TableKamar2.getColumnModel().getColumnCount() > 0) {
            TableKamar2.getColumnModel().getColumn(0).setResizable(false);
            TableKamar2.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        kamarPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 770, 190));

        jLabel16.setText("Cari Kode Kamar");
        kamarPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));
        kamarPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Search_15px_1.png"))); // NOI18N
        jLabel40.setToolTipText("Cari");
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kamarPanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 20, 20));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Trash_30px.png"))); // NOI18N
        jLabel44.setToolTipText("Hapus");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        kamarPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Edit_Property_30px.png"))); // NOI18N
        jLabel45.setToolTipText("Edit");
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        kamarPanel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 40, 30));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Plus_30px.png"))); // NOI18N
        jLabel46.setToolTipText("Tambah");
        jLabel46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        kamarPanel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 30, 50));

        bg.add(kamarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 790, 470));

        fasilitasPanel.setBackground(new java.awt.Color(255, 255, 255));
        fasilitasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 150, 136));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 58, 210, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Dasboard/Fasilitas");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        Close3.setForeground(new java.awt.Color(255, 255, 255));
        Close3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Close3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Delete_15px.png"))); // NOI18N
        Close3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close3MouseClicked(evt);
            }
        });
        jPanel4.add(Close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, 20));

        jLabel25.setFont(new java.awt.Font("Hobo Std", 1, 22)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("KOST Ibu Tuti");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, -1));
        jPanel4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, 10));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Jl. Kenangan No. 29 Bandung Tlp (022) - 2126453 ");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        logokostan7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Home_52px_3.png"))); // NOI18N
        jPanel4.add(logokostan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 50));

        fasilitasPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 130));

        tabelFasilitas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabelFasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Kode Transaksi", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelFasilitas);
        if (tabelFasilitas.getColumnModel().getColumnCount() > 0) {
            tabelFasilitas.getColumnModel().getColumn(0).setResizable(false);
            tabelFasilitas.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        fasilitasPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 770, 190));

        jLabel17.setText("Menurut");
        fasilitasPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, 20));
        fasilitasPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 120, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Search_15px_1.png"))); // NOI18N
        jLabel41.setToolTipText("Cari");
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        fasilitasPanel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 20, 20));

        hapusFasilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Trash_30px.png"))); // NOI18N
        hapusFasilitas.setToolTipText("Hapus");
        hapusFasilitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fasilitasPanel.add(hapusFasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        editFasilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Edit_Property_30px.png"))); // NOI18N
        editFasilitas.setToolTipText("Edit");
        editFasilitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editFasilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editFasilitasMouseClicked(evt);
            }
        });
        fasilitasPanel.add(editFasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 40, 30));

        tambahFasilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Plus_30px.png"))); // NOI18N
        tambahFasilitas.setToolTipText("Tambah");
        tambahFasilitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambahFasilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahFasilitasMouseClicked(evt);
            }
        });
        fasilitasPanel.add(tambahFasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 30, 50));

        jLabel50.setText("Cari Fasilitas");
        fasilitasPanel.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        bycarifasilitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "Nama" }));
        fasilitasPanel.add(bycarifasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        bg.add(fasilitasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 790, 470));

        transaksiPanel.setBackground(new java.awt.Color(255, 255, 255));
        transaksiPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 150, 136));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 58, 210, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Dasboard/Transaksi");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        Close4.setForeground(new java.awt.Color(255, 255, 255));
        Close4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Close4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Delete_15px.png"))); // NOI18N
        Close4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close4MouseClicked(evt);
            }
        });
        jPanel5.add(Close4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, 20));

        jLabel35.setFont(new java.awt.Font("Hobo Std", 1, 22)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("KOST Ibu Tuti");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, -1));
        jPanel5.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, 10));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Jl. Kenangan No. 29 Bandung Tlp (022) - 2126453 ");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        logokostan8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Home_52px_3.png"))); // NOI18N
        jPanel5.add(logokostan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 50));

        transaksiPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 130));

        tableTransaksi2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableTransaksi2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Kode Transaksi", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableTransaksi2);
        if (tableTransaksi2.getColumnModel().getColumnCount() > 0) {
            tableTransaksi2.getColumnModel().getColumn(0).setResizable(false);
            tableTransaksi2.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        transaksiPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 770, 190));

        jLabel18.setText("Cari Kode Transaksi");
        transaksiPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));
        transaksiPanel.add(txt_cariKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, -1));

        cariKode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Search_15px_1.png"))); // NOI18N
        cariKode.setToolTipText("Cari");
        cariKode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksiPanel.add(cariKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 20, 20));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Trash_30px.png"))); // NOI18N
        jLabel51.setToolTipText("Hapus");
        transaksiPanel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataGambar/icons8_Print_30px.png"))); // NOI18N
        jLabel52.setToolTipText("Cetak");
        jLabel52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        transaksiPanel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        bg.add(transaksiPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 790, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // menampilkan transaksi pada tanggal berdasarkan tanggal 
    void tampilDataTransaksiTerakhir() {
        TransaksiController transaksiCont = new TransaksiController();
        TransaksiModel transaksiModel = new TransaksiModel();
        tglTerakhir.setText(transaksiModel.setTanggalTerakhir());
        tabelTransaksi1.setModel(transaksiCont.tampilDataTerakhir());
        notifikasi();
    }
    void tampilDataTransaksi() {
        TransaksiController transaksi = new TransaksiController();
        tableTransaksi2.setModel(transaksi.tampilSemuaData());
    }
    
    void tammpilDataFasilitas() {
        FasilitasController fasilitas = new FasilitasController();
        tabelFasilitas.setModel(fasilitas.tampilData());
    }
    public void tampildatakamar(){
        KamarController kamar = new KamarController();
        TableKamar2.setModel(kamar.tampilData());
    }
    void tampildatapelanggan(){
        PelangganController pel = new PelangganController();
        tabelPelanggan.setModel(pel.tampilData());
    }
    void notifikasi() {
        KamarModel kmrModel = new KamarModel();
        for (String keterangan : kmrModel.setNotifikasi()) {
            if (keterangan == null) {
                break;
            }
            notif.append("Kode kamar "+keterangan+" akan segera habis !!\n");
        }
      
    }
    
    
    
    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void Close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_Close1MouseClicked

    private void Close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close2MouseClicked
       System.exit(0);
    }//GEN-LAST:event_Close2MouseClicked

    private void Close3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_Close3MouseClicked

    private void Close4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_Close4MouseClicked
    int xx, xy;
    private void sidePaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePaneMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_sidePaneMousePressed

    private void sidePaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePaneMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_sidePaneMouseDragged

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        halamanUtamaPanel.hide();
        pelangganPanel.show();
        kamarPanel.hide();
        fasilitasPanel.hide();
        transaksiPanel.hide();
        jLabel6.setForeground(Color.yellow);
        jLabel2.setForeground(Color.white);
        jLabel4.setForeground(Color.white);
        jLabel14.setForeground(Color.white);
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_menu2MouseClicked

    private void menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3MouseClicked
        halamanUtamaPanel.hide();
        pelangganPanel.hide();
        kamarPanel.show();
        fasilitasPanel.hide();
        transaksiPanel.hide();
        jLabel8.setForeground(Color.yellow);
        jLabel2.setForeground(Color.white);
        jLabel6.setForeground(Color.white);
        jLabel4.setForeground(Color.white);
        jLabel14.setForeground(Color.white);
    }//GEN-LAST:event_menu3MouseClicked

    private void menu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4MouseClicked
        halamanUtamaPanel.hide();
        pelangganPanel.hide();
        kamarPanel.hide();
        fasilitasPanel.show();
        transaksiPanel.hide();
        jLabel4.setForeground(Color.yellow);
        jLabel2.setForeground(Color.white);
        jLabel6.setForeground(Color.white);
        jLabel14.setForeground(Color.white);
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_menu4MouseClicked

    private void menu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu5MouseClicked
        halamanUtamaPanel.hide();
        pelangganPanel.hide();
        kamarPanel.hide();
        fasilitasPanel.hide();
        transaksiPanel.show();
        jLabel14.setForeground(Color.yellow);
        jLabel2.setForeground(Color.white);
        jLabel4.setForeground(Color.white);
        jLabel6.setForeground(Color.white);
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_menu5MouseClicked

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        halamanUtamaPanel.show();
        pelangganPanel.hide();
        kamarPanel.hide();
        fasilitasPanel.hide();
        transaksiPanel.hide();
        jLabel2.setForeground(Color.yellow);
        jLabel14.setForeground(Color.white);
        jLabel4.setForeground(Color.white);
        jLabel6.setForeground(Color.white);
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_menu1MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        new Tambah_pelanggan().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel37MouseClicked

    private void searchByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByActionPerformed

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
        new Edit_pelanggan().setVisible(true);
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
new Edit_kamar().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel45MouseClicked

    private void editFasilitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editFasilitasMouseClicked
new Edit_Fasilitas().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_editFasilitasMouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
        new Tambah_Kamar().setVisible(true);
    }//GEN-LAST:event_jLabel46MouseClicked

    private void tambahFasilitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahFasilitasMouseClicked
        new Tambah_fasilitas().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_tambahFasilitasMouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        
        try {
            KoneksiDB koneksi = new KoneksiDB();
            Connection conn = koneksi.getKoneksi();
            JasperDesign jd = JRXmlLoader.load("D:\\Netbeans_Project\\KostManagement-master\\Transaksi.jrxml");
            String sql = "SELECT `t_transaksi`.`kd_transaksi` , `t_transaksi`.`tgl_bayar` , `t_pelanggan`.`nama_lengkap` , `det_transaksi`.`total` FROM `det_transaksi` INNER JOIN `t_transaksi` ON (`det_transaksi`.`kd_transaksi` = `t_transaksi`.`kd_transaksi`) INNER JOIN `t_pelanggan` ON (`det_transaksi`.`kd_pelanggan` = `t_pelanggan`.`kd_pelanggan`)"
                    + "WHERE  t_transaksi.kd_transaksi = '"+getKodeTransaksi()+"'";

            JRDesignQuery JRD = new JRDesignQuery();
            JRD.setText(sql);
            jd.setQuery(JRD);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        String kodeFasilitas = txt_cariKode.getText();
        
        FasilitasController cariKode = new FasilitasController();
        
        if (bycarifasilitas.getSelectedItem() == "Kode") {
            cariKode.cariKodeFasilitas(kodeFasilitas);
        }
        tabelFasilitas.setModel(cariKode.cariKodeFasilitas(kodeFasilitas));
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        
        
    }//GEN-LAST:event_jLabel44MouseClicked

    private void cariDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariDataMouseClicked
        String cari = txt_cariData.getText();
        PelangganController cariPelanggan = new PelangganController();
        
        if (searchBy.getSelectedItem() == "Kode") {
            cariPelanggan.cariKodePelanggan(cari);
        }
    }//GEN-LAST:event_cariDataMouseClicked
    
   
    public String getKodeTransaksi() {
        row = tableTransaksi2.getSelectedColumn();
        String kodeTransaksi = tableTransaksi2.getValueAt(row, 0).toString();
        return kodeTransaksi;
    }
     int rowkamar = 0;
    public String getKodeKamar() {
        row = TableKamar2.getSelectedColumn();
        String kodekamar = TableKamar2.getValueAt(row, 0).toString();
        return kodekamar;
    }
   // public String getluaskamar() {
      //  rowkamar = TableKamar2.getSelectedColumn();
      //  String luas = TableKamar2.getValueAt(rowkamar, 1).toString();
      //  return luas;
  //  }
   /// public String getHargaKamar() {
      //  rowkamar = TableKamar2.getSelectedColumn();
       // String Harga = TableKamar2.getValueAt(rowkamar, 2).toString();
       // return Harga;
    //}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HalamanUtama().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Close2;
    private javax.swing.JLabel Close3;
    private javax.swing.JLabel Close4;
    private javax.swing.JTable TableKamar2;
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> bycarifasilitas;
    private javax.swing.JLabel cariData;
    private javax.swing.JLabel cariKode;
    private javax.swing.JLabel editFasilitas;
    private javax.swing.JPanel fasilitasPanel;
    private javax.swing.JPanel halamanUtamaPanel;
    private javax.swing.JLabel hapusFasilitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel kamarPanel;
    private javax.swing.JLabel logokostan;
    private javax.swing.JLabel logokostan5;
    private javax.swing.JLabel logokostan6;
    private javax.swing.JLabel logokostan7;
    private javax.swing.JLabel logokostan8;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    private javax.swing.JPanel menu4;
    private javax.swing.JPanel menu5;
    private javax.swing.JTextArea notif;
    private javax.swing.JPanel notifikasi;
    private javax.swing.JPanel pelangganPanel;
    private javax.swing.JComboBox<String> searchBy;
    private javax.swing.JPanel sidePane;
    private javax.swing.JTable tabelFasilitas;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JTable tabelTransaksi1;
    private javax.swing.JTable tableTransaksi2;
    private javax.swing.JLabel tambahFasilitas;
    private javax.swing.JLabel tglTerakhir;
    private javax.swing.JPanel transaksiPanel;
    private javax.swing.JTextField txt_cariData;
    private javax.swing.JTextField txt_cariKode;
    // End of variables declaration//GEN-END:variables

    public void getClass(KamarController kamar) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
